# https://travis-ci.org/caesarhao/AgileDoctorDB
language: java
jdk:
    - oraclejdk8
    - openjdk7

notifications:
  email: false


script:
	- jdk_switcher use oraclejdk8
	- bash build.sh
	- jdk_switcher use openjdk7
	- bash build.sh

