# https://travis-ci.org/caesarhao/AgileDoctorDB
language: java
jdk:
    - oraclejdk8
    - openjdk8

notifications:
  email: false


script:
	- jdk_switcher use oraclejdk8
	- ./build.sh
	- jdk_switcher use openjdk8
	- ./build.sh

