ALTER TABLE FamilyInformation DROP CONSTRAINT FK_FamilyInformation_ID
ALTER TABLE MedicalInformation DROP CONSTRAINT FK_MedicalInformation_ID
ALTER TABLE APatientInformation_DoctorPhrase DROP CONSTRAINT PatientInformationDoctorPhrasePatientInformationID
ALTER TABLE APatientInformation_DoctorPhrase DROP CONSTRAINT PatientInformationDoctorPhrasepossibleAskPhrasesID
ALTER TABLE APatientInformation_PatientPhrase DROP CONSTRAINT PtientInformationPatientPhrasePatientInformationID
ALTER TABLE APatientInformation_PatientPhrase DROP CONSTRAINT PtntInformationPatientPhrasepssblResponsePhrasesID
ALTER TABLE APatientInformation_APatientInformation DROP CONSTRAINT PtntnformationAPatientInformationPtntInformationID
ALTER TABLE APatientInformation_APatientInformation DROP CONSTRAINT PtentInformationAPatientInformationsbnformationsID
ALTER TABLE MicroSequence_DialogueSession DROP CONSTRAINT MicroSequence_DialogueSession_dialogueSessions_ID
ALTER TABLE MicroSequence_DialogueSession DROP CONSTRAINT FK_MicroSequence_DialogueSession_MicroSequence_ID
ALTER TABLE Scenario_MicroSequence DROP CONSTRAINT FK_Scenario_MicroSequence_microSequences_ID
ALTER TABLE Scenario_MicroSequence DROP CONSTRAINT FK_Scenario_MicroSequence_Scenario_ID
DROP TABLE APatientInformation
DROP TABLE DialogueSession
DROP TABLE DoctorActor
DROP TABLE DoctorPhrase
DROP TABLE FamilyInformation
DROP TABLE MedicalInformation
DROP TABLE MicroSequence
DROP TABLE PatientActor
DROP TABLE PatientPhrase
DROP TABLE Scenario
DROP TABLE APatientInformation_DoctorPhrase
DROP TABLE APatientInformation_PatientPhrase
DROP TABLE APatientInformation_APatientInformation
DROP TABLE MicroSequence_DialogueSession
DROP TABLE Scenario_MicroSequence
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN_IDENTITY'
