ALTER TABLE FamilyInformation DROP CONSTRAINT FK_FamilyInformation_ID
ALTER TABLE MedicalInformation DROP CONSTRAINT FK_MedicalInformation_ID
ALTER TABLE APatientInformation_Phrase DROP CONSTRAINT APatientInformation_Phrase_APatientInformation_ID
ALTER TABLE APatientInformation_Phrase DROP CONSTRAINT APatientInformation_Phrase_possibleAskPhrases_ID
ALTER TABLE APatientInformation_Phrase DROP CONSTRAINT APatientInformationPhrasepossibleResponsePhrasesID
ALTER TABLE APatientInformation_APatientInformation DROP CONSTRAINT PtntnformationAPatientInformationPtntInformationID
ALTER TABLE APatientInformation_APatientInformation DROP CONSTRAINT PtentInformationAPatientInformationsbnformationsID
ALTER TABLE MicroSequence_DialogueSession DROP CONSTRAINT MicroSequence_DialogueSession_dialogueSessions_ID
ALTER TABLE MicroSequence_DialogueSession DROP CONSTRAINT FK_MicroSequence_DialogueSession_MicroSequence_ID
ALTER TABLE Scenario_MicroSequence DROP CONSTRAINT FK_Scenario_MicroSequence_microSequences_ID
ALTER TABLE Scenario_MicroSequence DROP CONSTRAINT FK_Scenario_MicroSequence_Scenario_ID
DROP TABLE APatientInformation
DROP TABLE DialogueSession
DROP TABLE DoctorActor
DROP TABLE FamilyInformation
DROP TABLE MedicalInformation
DROP TABLE MicroSequence
DROP TABLE PatientActor
DROP TABLE Phrase
DROP TABLE Scenario
DROP TABLE APatientInformation_Phrase
DROP TABLE APatientInformation_APatientInformation
DROP TABLE MicroSequence_DialogueSession
DROP TABLE Scenario_MicroSequence
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN_IDENTITY'
